import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerInitTool } from './init.js';
import { registerSetDirectivesTool } from './directives.js';
import { registerPlanTool } from './plan.js';
import { registerStartTool } from './start.js';
import { registerStatusTool } from './status.js';
import { registerDoctorTool } from './doctor.js';
import { registerRetroTool } from './retro.js';
import { registerHistoryTool } from './history.js';
import { registerAnalyzeTool } from './analyze.js';
import { registerSyncTool } from './sync.js';
import { registerConfigTool } from './config.js';
import { registerReviewTool } from './review.js';
import { registerRunTool } from './run.js';
import { registerKillTool } from './kill.js';
import { registerCleanupTool } from './cleanup.js';
import { registerHelpTool } from './help.js'; // deckent_help
import { registerAgentListTool } from './agent-list.js';
import { registerSkillListTool } from './skill-list.js';
import { registerCheckpointTool } from './checkpoint.js';
import { registerDocsTool } from './docs.js';
import { registerExplainTool } from './explain.js';
import { registerMemoryQueryTool } from './memory-query.js';
import { registerWatch } from './watch.js';
import { registerNervousTools } from './nervous.js';
import { registerFeatureQueryTool } from './feature-query.js';
import { registerAuditTool } from './audit.js';
import { registerRecoverTool } from './recover.js';
import { registerModelsTool } from './models.js';
import { registerAutonomousTool } from './autonomous.js';

export function registerTools(server: McpServer): void {
  registerInitTool(server);
  registerSetDirectivesTool(server);
  registerPlanTool(server);
  registerStartTool(server);
  registerStatusTool(server);
  registerDoctorTool(server);
  registerRetroTool(server);
  registerHistoryTool(server);
  registerAnalyzeTool(server);
  registerSyncTool(server);
  registerConfigTool(server);
  registerReviewTool(server);
  registerRunTool(server);
  registerKillTool(server);
  registerCleanupTool(server);
  registerHelpTool(server);
  registerAgentListTool(server);
  registerSkillListTool(server);
  registerCheckpointTool(server);
  registerDocsTool(server);
  registerExplainTool(server);
  registerMemoryQueryTool(server);
  registerWatch(server);
  registerNervousTools(server);
  registerFeatureQueryTool(server);
  registerAuditTool(server);
  registerRecoverTool(server);
  registerModelsTool(server);
  registerAutonomousTool(server);
}
