// ─── WORKER-GIT-GUARD (381-001) ────────────────────────────────────────────
// KOK-NEDEN: a worker CLI (claude --dangerously-skip-permissions) runs inside
// an RW-mounted repo and can invoke `git stash` / `git reset --hard` / etc.
// directly — `rollback.ts:detectDeckentRepo` only guards deckent's OWN
// rollback path, never the worker's own git invocations, and
// worker-default.md carries no git ban. This module builds a `git` shim
// script that denies a fixed set of destructive subcommands and installs it
// ahead of the real `git` on PATH for all 3 spawn backends
// (spawn-backend-docker.ts, providers/subprocess.ts, tmux.ts).
//
// Honest scope (ADVISORY, not a hardened sandbox): the shim matches `$1`
// literally (no global-flag-prefix parsing, e.g. `git -C x stash` is not
// caught) and a worker's shell always has direct access to the real git
// binary by absolute path — this closes the *accidental / default-PATH*
// case the incident showed, mirroring the project's existing runtime-soft
// RBAC boundary (ADR-D-004 gotcha: "Scope enforcement ... runtime
// advisory/soft").

import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { join, delimiter } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { debugLog } from '../core/utils.js';

// ─── Denylist ───────────────────────────────────────────────────────────

/** Destructive git subcommands a worker must never run. Matched against `$1` only. */
export const GIT_GUARD_DENYLISTED_SUBCOMMANDS = [
  'stash',
  'reset',
  'checkout',
  'clean',
  'rebase',
  'commit',
  'revert',
] as const;

/** Exit code a blocked invocation returns — deliberately outside the common 0-2/124/137 range. */
export const GIT_GUARD_BLOCKED_EXIT_CODE = 97;

/**
 * Fallback git path when {@link resolveHostGitPath}'s PATH scan finds nothing
 * (Debian/Ubuntu apt default — also matches Dockerfile.worker's install path).
 */
const DEFAULT_GIT_PATH_POSIX = '/usr/bin/git';
const DEFAULT_GIT_PATH_WIN32 = 'git.exe';

/**
 * Container git path for the docker backend. Hardcoded rather than probed:
 * Dockerfile.worker installs git via `apt-get install git` on
 * `node:24-trixie-slim` (standard Debian layout), a host-side `existsSync`
 * scan cannot see inside the container filesystem, and probing the image via
 * an extra `docker run --rm <image> which git` would add a SECOND docker
 * invocation per spawn — breaking the "exactly one docker run per spawn"
 * assumption several spawn-backend-docker.test.ts cases assert (same
 * rationale `probeProviderCliPresentInImage` already documents for staying
 * opt-in-only in this same file).
 */
export const CONTAINER_GIT_PATH = '/usr/bin/git';

function escapeSingleQuoted(value: string): string {
  return value.replace(/'/g, `'\\''`);
}

/**
 * Co-located bilingual (en/tr) denylist message — NOT sourced from
 * `src/cli/helpers/messages.ts`. `git-worker-guard.ts` lives in
 * `src/orchestra/`, and ADR-D-004 C2 forbids `orchestra/ → cli/` imports;
 * this mirrors the exact precedent already established in
 * `sprint-phases.ts:finalizeFailedMessage` (ORCH-W1) for orchestra-layer
 * i18n needs. ASCII-only Turkish (no diacritics) deliberately — this string
 * is baked into a POSIX `sh` script written to disk and `echo`'d by whatever
 * shell is present (dash / busybox sh / bash) inside a container or host
 * subprocess; ASCII avoids any locale/encoding surprise across that matrix.
 */
function gitGuardDenyMessage(lang: string): { prefix: string; suffix: string } {
  if (lang === 'tr') {
    return {
      prefix: 'deckent WORKER-GIT-GUARD: git ',
      suffix:
        ' worker calistirmalari icin engellendi (yikici git alt-komutu, denylist)'
        + ' - sadece salt-okunur git komutlarina izin verilir.',
    };
  }
  return {
    prefix: 'deckent WORKER-GIT-GUARD: git ',
    suffix: ' is blocked for workers (destructive git subcommand, denylisted) — only read-only git commands are allowed.',
  };
}

/**
 * Build the POSIX `sh` git shim script content. Denylisted subcommands
 * (matched against `$1` only) print a localized message to stderr and exit
 * {@link GIT_GUARD_BLOCKED_EXIT_CODE}; everything else — including unknown
 * subcommands — execs the real git binary unchanged (permissive default:
 * read-only git, e.g. `status`/`diff`/`show`, must never break).
 */
export function buildGitGuardShim(realGitPath: string, lang: string = 'en'): string {
  const { prefix, suffix } = gitGuardDenyMessage(lang);
  const denylistPattern = GIT_GUARD_DENYLISTED_SUBCOMMANDS.join('|');
  return [
    '#!/bin/sh',
    '# deckent WORKER-GIT-GUARD (381-001) — denies destructive git subcommands for workers.',
    '# Generated by src/orchestra/git-worker-guard.ts:buildGitGuardShim(). Do not edit by hand.',
    `REAL_GIT='${escapeSingleQuoted(realGitPath)}'`,
    'case "$1" in',
    `  ${denylistPattern})`,
    `    echo "${prefix}$1${suffix}" >&2`,
    `    exit ${GIT_GUARD_BLOCKED_EXIT_CODE}`,
    '    ;;',
    'esac',
    'exec "$REAL_GIT" "$@"',
    '',
  ].join('\n');
}

/**
 * Build an isolated git-guard shim directory OUTSIDE the project tree — under
 * the OS tmpdir, keyed by `taskId` plus a random per-call suffix (same
 * `randomBytes` pattern the docker backend already uses for its own promptId
 * uniqueness). Deliberately NOT derived from the project directory: a
 * project-relative path (e.g. `<projectDir>/.tasks/.git-guard-<taskId>`)
 * ends up verbatim inside a `PATH` env var, which breaks the subprocess
 * backend's DeckBroker non-leak invariant (DECKBROKER-WIRE, 354-006 —
 * "the .deck project path never appears in the spawned child env") the
 * moment `installGitGuard`'s directory is folded into `childEnv.PATH`. The
 * random suffix also makes two different projects spawning the same
 * (sprint-scoped, not globally unique) `taskId` on a shared host collision-safe.
 */
export function buildGitGuardDir(taskId: string): string {
  const token = randomBytes(4).toString('hex');
  return join(tmpdir(), 'deckent-git-guard', `${taskId}-${token}`);
}

/** Result of {@link installGitGuard} — what to feed into a backend's PATH. */
export interface GitGuardInstall {
  /** Host directory the shim was written into. */
  shimDir: string;
  /** PATH entry to prepend so the shim shadows the real `git` (equals `shimDir`). */
  pathPrefix: string;
}

/**
 * Write the git shim to `dir/git` (mode 0o755) and return the directory to
 * prepend onto PATH. Idempotent: an existing file at the same path (e.g. a
 * priority-fix retry re-spawn with the same taskId) is overwritten and its
 * mode re-asserted — mirrors `ensureDeckShadowFile`'s STALE-SHADOW-PERMS
 * defense (writeFileSync's `mode` option only applies on CREATE, not on an
 * O_TRUNC overwrite of a pre-existing file).
 */
export function installGitGuard(dir: string, realGitPath: string, lang: string = 'en'): GitGuardInstall {
  mkdirSync(dir, { recursive: true });
  const shimPath = join(dir, 'git');
  writeFileSync(shimPath, buildGitGuardShim(realGitPath, lang), { mode: 0o755 });
  try {
    chmodSync(shimPath, 0o755);
  } catch (e) {
    debugLog('git-worker-guard:install-chmod', e);
  }
  return { shimDir: dir, pathPrefix: dir };
}

/**
 * Best-effort HOST git-binary resolution — scans `PATH` directories via
 * `existsSync` (a stat syscall, not a subprocess). Deliberately NOT
 * `spawnSync('which', ...)`: `spawn-backend-docker.ts` and `tmux.ts` are both
 * on the `no-new-spawnSync` hot-path list
 * (scripts/spawnsync-baseline.json HOT_PATH_FILES) — a new spawnSync call
 * site there is a hard lint failure, never grandfatherable via `--update`.
 * Falls back to the platform default when nothing is found on PATH.
 */
export function resolveHostGitPath(
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform = process.platform,
): string {
  const pathVar = env['PATH'] ?? env['Path'] ?? '';
  const binName = platform === 'win32' ? 'git.exe' : 'git';
  for (const dir of pathVar.split(delimiter)) {
    if (!dir) continue;
    const candidate = join(dir, binName);
    if (existsSync(candidate)) return candidate;
  }
  return platform === 'win32' ? DEFAULT_GIT_PATH_WIN32 : DEFAULT_GIT_PATH_POSIX;
}

/**
 * `export PATH=...` line shadowing the real `git` with the shim directory.
 * Shared building block for the docker in-container script and the tmux
 * `send-keys` command prefix.
 */
export function buildGitGuardPathExport(shimDir: string): string {
  return `export PATH="${shimDir}:$PATH"`;
}

/**
 * Docker backend wiring: a read-only bind-mount (mirrors the `.deck`
 * shadow-mount pattern — a worker cannot `rm`/edit a `:ro` mount to bypass
 * the guard) plus the in-container `PATH` export line.
 */
export interface DockerGitGuardArgs {
  /** `docker run` args to append (a `-v host:container:ro` pair). */
  mountArgs: string[];
  /** In-container path the shim directory is mounted at. */
  containerShimDir: string;
  /** Script line to place before the worker command runs. */
  exportPathLine: string;
}

export function buildDockerGitGuardArgs(hostShimDir: string, containerWorkspace: string): DockerGitGuardArgs {
  const containerShimDir = `${containerWorkspace}/.git-guard-bin`;
  return {
    mountArgs: ['-v', `${hostShimDir}:${containerShimDir}:ro`],
    containerShimDir,
    exportPathLine: buildGitGuardPathExport(containerShimDir),
  };
}

/** Prepend the shim directory onto an existing `PATH` value (subprocess backend's plain env, no shell involved). */
export function prependGitGuardToPath(shimDir: string, currentPath: string | undefined): string {
  return currentPath ? `${shimDir}${delimiter}${currentPath}` : shimDir;
}

/**
 * Whether the POSIX shim is usable on this platform. `false` on win32: a
 * `#!/bin/sh` file named `git` is never resolved by Windows' PATHEXT-based
 * executable lookup, so installing it there would be a SILENT no-op guard
 * (Law #2: an unsupported platform must fail honestly, never silently) —
 * callers must skip installation and log the gap instead.
 */
export function isGitGuardSupportedPlatform(platform: NodeJS.Platform = process.platform): boolean {
  return platform !== 'win32';
}
