// ─── run-proposal-compiler — TERM-FLOW-UNIFY Sprint-2 dilim (424-001) ──────
//
// docs/analysis/term-flow-unify-design-2026-07-11.md ("Organ nakli olacak
// parçalar"): directives-builder.ts stays the code-repo proposal ADAPTER —
// this module is that adapter's other end. It turns a domain-general
// `RunProposal` (core/run-flow-contract.ts, sprint-422 contract — no
// DIRECTIVES/files/scope fields by design) into a `DirectiveBuildIntent` and
// then calls the UNCHANGED `buildDirectives()` to render markdown. Zero
// modification to directives-builder.ts — it is called, never touched.
//
// Same scoping boundary buildPlanNlIntent (cli/commands/plan-nl.ts) already
// draws for a raw NL goal string: a single-task TODO-scaffold, not real NL
// decomposition. Real multi-task decomposition from a RunProposal is the
// explicit native-flow follow-up (design doc Sprint 3, "Native
// proposal/card/approval") — this slice only needs a deterministic,
// lossless RunProposal -> DIRECTIVES-markdown adapter.
//
// Proposal metadata (flowId/tenant/project/actor/origin/revision) is folded
// into the task description as plain traceability prose — never as a
// "Label: value" line — so it can never collide with directives-builder's
// RESERVED_LABEL_RE / heading guards (assertSafeField, buildTaskBlock).

import type { RunProposal } from '../core/run-flow-contract.js';
import { buildDirectives, type DirectiveBuildIntent } from './directives-builder.js';

export interface RunProposalCompileResult {
  readonly intent: DirectiveBuildIntent;
  readonly directivesMarkdown: string;
}

function describeActor(proposal: RunProposal): string {
  const { actor } = proposal;
  return actor.role ? `${actor.id} (${actor.role})` : actor.id;
}

/**
 * Map a `RunProposal` to a single-task {@link DirectiveBuildIntent} scaffold.
 * Files/Scope/goCriteria/nogo are explicit TODO placeholders (same boundary
 * as buildPlanNlIntent) — a future native-flow decomposition step replaces
 * this with real multi-task planning; this adapter only guarantees a
 * lossless, deterministic RunProposal -> DirectiveBuildIntent mapping.
 */
export function compileRunProposalIntent(proposal: RunProposal): DirectiveBuildIntent {
  const intentSummary = proposal.intentSummary.trim();
  const traceability =
    `RunProposal metadata — flowId=${proposal.flowId}, revision=${proposal.revision}, ` +
    `tenant=${proposal.tenant}, project=${proposal.project}, actor=${describeActor(proposal)}, ` +
    `origin=${proposal.origin}.`;

  return {
    title: `RunProposal ${proposal.flowId}`,
    goal: intentSummary,
    tasks: [
      {
        title: intentSummary,
        desc:
          `${intentSummary}\n\n${traceability}\n\n` +
          'Auto-generated by run-proposal-compiler.ts from a host-owned RunProposal — this is a ' +
          'single-task SCAFFOLD, not a ready-to-run plan. RunProposal to multi-task decomposition ' +
          'is a follow-up (native proposal/card/approval sprint); fill in the TODO placeholders ' +
          'below to match the real work before this proposal is approved and started.',
        files: ['TODO-fill-in-target-files'],
        scope: ['TODO-fill-in-scope/'],
        deps: [],
        goCriteria: [`TODO: define verifiable done-criteria for "${intentSummary}"`],
        nogo: ['TODO: define what must NOT happen'],
      },
    ],
  };
}

/**
 * Compile a `RunProposal` straight to DIRECTIVES.md markdown. Calls
 * buildDirectives() purely (in-memory, no fs) — this function never writes
 * DIRECTIVES.md or any other file itself; that stays the caller's job.
 */
export function compileRunProposal(proposal: RunProposal): RunProposalCompileResult {
  const intent = compileRunProposalIntent(proposal);
  const directivesMarkdown = buildDirectives(intent);
  return { intent, directivesMarkdown };
}
