import { createHmac, timingSafeEqual } from 'node:crypto';
import { chmodSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { ApprovalBroker } from '../../src/core/approval-broker.js';
import { ApprovalDecisionAuthority, ApprovalDecisionIngress, type ApprovalDecisionIntegrityAuthority, type LiveApprovalAuthentication, type LiveApprovalAuthenticator, type LiveApprovalSessionProof } from '../../src/core/approval-decision-ingress.js';
import { ProviderExecutionObservationReconciliationApprovalAuthority } from '../../src/core/provider-execution-observation-reconciliation-approval.js';
import { applyProviderExecutionObservationReconciliation, inventoryProviderExecutionObservationReconciliation, planProviderExecutionObservationReconciliation } from '../../src/core/provider-execution-observation-reconciliation.js';
import { ProviderExecutionObservationStore } from '../../src/core/provider-execution-observation-store.js';
import { claimTaskResultSettlementAttemptAtomic, createTaskResultSettlement, createTaskResultSettlementRefForAttempt, writeTaskResultSettlementAtomic, writeTaskResultSettlementAttemptAtomic, writeTaskResultSettlementClosureAtomic } from '../../src/core/task-result-settlement.js';
import { deriveProviderExecutionObservationReconciliationReceiptScope, discoverProviderExecutionObservationReconciliationReceipts, parseProviderExecutionObservationReconciliationReceipt, publishProviderExecutionObservationReconciliationReceipt, readProviderExecutionObservationReconciliationReceipt } from '../../src/core/provider-execution-observation-reconciliation-receipt-store.js';
const roots: string[] = []; const homes: string[] = []; const originalHome = process.env.DECKENT_HOME; const ATTEMPT = '11111111-1111-4111-8111-111111111111';
const NOW = new Date('2026-08-23T00:00:04.000Z'); const KEY = Buffer.from('reconciliation-receipt-approval-key');
class Integrity implements ApprovalDecisionIntegrityAuthority { sign(payload: string) { return { keyId: 'key', mac: createHmac('sha256', KEY).update(payload).digest('hex') }; } verify(keyId: string, payload: string, mac: string) { const expected = this.sign(payload).mac; return keyId === 'key' && mac.length === expected.length && timingSafeEqual(Buffer.from(mac, 'hex'), Buffer.from(expected, 'hex')); } }
class Authenticator implements LiveApprovalAuthenticator { readonly identity: LiveApprovalAuthentication = { actorId: 'approver', tenantId: 'tenant/a', role: 'owner', sessionRef: 'session', authorityRef: 'terminal', authenticatedAt: NOW.toISOString(), expiresAt: new Date(NOW.getTime() + 120_000).toISOString() }; async reauthenticate() { return this.identity; } isSessionActive(proof: LiveApprovalSessionProof) { return proof.actorId === this.identity.actorId && proof.tenantId === this.identity.tenantId; } }
afterEach(() => { if (originalHome === undefined) delete process.env.DECKENT_HOME; else process.env.DECKENT_HOME = originalHome; for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); for (const home of homes.splice(0)) rmSync(home, { recursive: true, force: true }); });
function close(root: string, taskId: string, attemptId: string): void { const ref = createTaskResultSettlementRefForAttempt(root, taskId, attemptId); writeTaskResultSettlementAttemptAtomic(ref, '2026-08-23T00:00:00.000Z'); claimTaskResultSettlementAttemptAtomic(ref, '2026-08-23T00:00:01.000Z'); writeTaskResultSettlementAtomic(createTaskResultSettlement({ ref, exitCode: 0, settledAt: '2026-08-23T00:00:02.000Z', result: { taskId } })); writeTaskResultSettlementClosureAtomic(ref, { containerDisposition: 'absent-after-exit', locksReleased: true, closedAt: '2026-08-23T00:00:03.000Z' }); }
async function fixture() { const root = mkdtempSync(join(tmpdir(), 'deckent-reconciliation-receipt-')); const home = mkdtempSync(join(tmpdir(), 'deckent-reconciliation-receipt-home-')); roots.push(root); homes.push(home); process.env.DECKENT_HOME = home; const dbPath = join(root, '.deckent', 'provider-execution-observations.db'); const store = new ProviderExecutionObservationStore(root, { dbPath }); store.put({ source: 'provider-runtime', observation: { type: 'start', executionId: 'execution-1', taskId: 'task-1', attemptId: ATTEMPT, runId: 'run-1', providerPrincipalDigest: 'principal-a', fence: 'fence-a', sequence: 1, observedAt: '2026-08-23T00:00:00.000Z' } }); close(root, 'task-1', ATTEMPT); const plan = planProviderExecutionObservationReconciliation({ inventory: inventoryProviderExecutionObservationReconciliation({ projectRoot: root }), canonicalRunId: 'run-1' }); const broker = new ApprovalBroker(root, { clock: () => NOW }); const integrity = new Integrity(); const authenticator = new Authenticator(); const authority = new ProviderExecutionObservationReconciliationApprovalAuthority(root, broker, new ApprovalDecisionAuthority(integrity, authenticator), { now: () => NOW }); const ingress = new ApprovalDecisionIngress({ broker, authenticator, integrity, channel: 'terminal', now: () => NOW }); const approval = { plan, tenantId: 'tenant/a', requestedBy: 'brain', approverUserId: 'approver', generation: 'run-1', expiresAt: new Date(NOW.getTime() + 60_000).toISOString(), requester: { role: 'brain' as const, instanceId: 'receipt-test' } }; const request = authority.submit(approval); await ingress.decide({ requestId: request.id, action: 'allow', idempotencyKey: 'receipt-allow' }); const result = authority.apply({ requestId: request.id, plan, tenantId: approval.tenantId, requestedBy: approval.requestedBy, generation: approval.generation, expiresAt: approval.expiresAt }); if (result.state === 'hold') throw new Error(result.reasonCode); return { root, store, plan, result }; }
function input(value: ReturnType<typeof fixture>) { return { projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu', plan: value.plan, result: value.result, verifiedAt: '2026-08-23T00:00:04.000Z' } as const; }
function code(action: () => unknown, expected: string) { expect(action).toThrowError(expect.objectContaining({ code: expected })); }
describe('provider execution observation reconciliation receipt store', () => {
  it('binds the verified approval claim into a private content-addressed receipt', async () => { const value = await fixture(); const published = publishProviderExecutionObservationReconciliationReceipt(input(value)); expect(published.receipt).toMatchObject({ state: 'applied', retiredCount: 1, approvalClaim: value.result.claim, planDigest: `sha256:${value.plan.planDigest}` }); expect(readProviderExecutionObservationReconciliationReceipt({ projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu', receiptId: published.receipt.receiptId, fresh: true })).toEqual(published.receipt); expect(JSON.stringify(published.receipt)).not.toContain('tenant/a'); code(() => publishProviderExecutionObservationReconciliationReceipt({ ...input(value), result: { ...value.result, claim: { ...value.result.claim } } }), 'RECONCILIATION_MISMATCH'); value.store.close(); });
  it('rejects approval and candidate receipt tampering', async () => { const value = await fixture(); const published = publishProviderExecutionObservationReconciliationReceipt(input(value)); const bytes = readFileSync(join(value.root, ...published.projectRelativeReceiptPath.split('/')), 'utf8'); const approvalTamper = JSON.parse(bytes) as { approvalClaim: { decisionDigest: string } }; approvalTamper.approvalClaim.decisionDigest = 'f'.repeat(64); code(() => parseProviderExecutionObservationReconciliationReceipt(JSON.stringify(approvalTamper)), 'INVALID_RECEIPT'); const candidateTamper = JSON.parse(bytes) as { retiredExecutions: Array<{ executionId: string }> }; candidateTamper.retiredExecutions[0]!.executionId = 'forged'; code(() => parseProviderExecutionObservationReconciliationReceipt(JSON.stringify(candidateTamper)), 'INVALID_RECEIPT'); value.store.close(); });
  it('uses monotonic candidate-specific freshness after legitimate unrelated appends and retirements', async () => { const value = await fixture(); const published = publishProviderExecutionObservationReconciliationReceipt(input(value)); value.store.put({ source: 'provider-runtime', observation: { type: 'start', executionId: 'later', taskId: 'later', attemptId: '22222222-2222-4222-8222-222222222222', runId: 'run-2', providerPrincipalDigest: 'principal-a', fence: 'fence-a', sequence: 2, observedAt: '2026-08-23T00:00:05.000Z' } }); close(value.root, 'later', '22222222-2222-4222-8222-222222222222'); const laterPlan = planProviderExecutionObservationReconciliation({ inventory: inventoryProviderExecutionObservationReconciliation({ projectRoot: value.root }), canonicalRunId: 'run-2' }); applyProviderExecutionObservationReconciliation({ plan: laterPlan }); expect(readProviderExecutionObservationReconciliationReceipt({ projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu', receiptId: published.receipt.receiptId, fresh: true })).toEqual(published.receipt); value.store.close(); });
  it('fails fresh verification when an exact candidate is no longer retired', async () => { const value = await fixture(); const published = publishProviderExecutionObservationReconciliationReceipt(input(value)); const store = value.store as unknown as { db: { prepare(sql: string): { run(...args: unknown[]): void } } }; store.db.prepare('UPDATE provider_execution_intervals SET retired = 0 WHERE execution_id = ?').run('execution-1'); code(() => readProviderExecutionObservationReconciliationReceipt({ projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu', receiptId: published.receipt.receiptId, fresh: true }), 'LINEAGE_MISMATCH'); value.store.close(); });
  it.skipIf(process.platform === 'win32')('rejects unsafe links, permissive paths, and over-bounded discovery', async () => { const value = await fixture(); const scope = deriveProviderExecutionObservationReconciliationReceiptScope({ projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu' }); const base = join(value.root, '.deckent'); symlinkSync(value.root, join(base, 'provider-execution-observation-reconciliation')); code(() => publishProviderExecutionObservationReconciliationReceipt(input(value)), 'UNSAFE_LINK'); rmSync(join(base, 'provider-execution-observation-reconciliation')); const first = publishProviderExecutionObservationReconciliationReceipt(input(value)); const directory = join(value.root, ...first.projectRelativeReceiptPath.split('/').slice(0, -1)); chmodSync(directory, 0o755); code(() => publishProviderExecutionObservationReconciliationReceipt({ ...input(value), verifiedAt: '2026-08-23T00:00:05.000Z' }), 'PERMISSION_DENIED'); chmodSync(directory, 0o700); writeFileSync(join(directory, 'ignored.tmp'), 'x', { mode: 0o600 }); code(() => discoverProviderExecutionObservationReconciliationReceipts({ projectRoot: value.root, tenantId: 'tenant/a', environmentId: 'prod/eu', maxEntries: 1 }), 'DISCOVERY_LIMIT_EXCEEDED'); expect(scope.environmentKey).not.toContain('prod'); value.store.close(); });
});
