import type { MessageFamily } from './cli-common.js';

/** User-facing chrome for the generated CLI reference. */
export const CLI_REFERENCE_MESSAGES: MessageFamily = Object.freeze({
  'cli.reference.title': { en: 'CLI Reference', tr: 'CLI Referansı' },
  'cli.reference.generated': {
    en: 'Auto-generated from the canonical CLI contract and the live Commander tree. Do not edit by hand.',
    tr: 'Canonical CLI contract ve canlı Commander tree üzerinden otomatik üretilir. Elle düzenlemeyin.',
  },
  'cli.reference.regenerate': {
    en: 'Run `npm run docs:generate-cli` to regenerate this document.',
    tr: 'Bu belgeyi yeniden üretmek için `npm run docs:generate-cli` çalıştırın.',
  },
  'cli.reference.intro': {
    en: 'This reference covers every public command path, option, positional argument, effect, default execution, authority, output mode, platform contract, and alias.',
    tr: 'Bu referans her public command path, option, positional argument, effect, default execution, authority, output mode, platform contract ve alias bilgisini kapsar.',
  },
  'cli.reference.index': { en: 'Command index', tr: 'Komut dizini' },
  'cli.reference.contract': { en: 'Execution contract', tr: 'Yürütme sözleşmesi' },
  'cli.reference.options': { en: 'Options', tr: 'Seçenekler' },
  'cli.reference.arguments': { en: 'Arguments', tr: 'Argümanlar' },
  'cli.reference.long_description': { en: 'Details', tr: 'Ayrıntılar' },
  'cli.reference.none': { en: 'None', tr: 'Yok' },
  'cli.reference.yes': { en: 'Yes', tr: 'Evet' },
  'cli.reference.no': { en: 'No', tr: 'Hayır' },
  'cli.reference.col.command': { en: 'Command', tr: 'Komut' },
  'cli.reference.col.description': { en: 'Description', tr: 'Açıklama' },
  'cli.reference.col.effect': { en: 'Effect', tr: 'Etki' },
  'cli.reference.col.default_execution': { en: 'Default execution', tr: 'Varsayılan yürütme' },
  'cli.reference.col.authority': { en: 'Authority', tr: 'Yetki' },
  'cli.reference.col.output': { en: 'Output', tr: 'Çıktı' },
  'cli.reference.col.platforms': { en: 'Platforms', tr: 'Platformlar' },
  'cli.reference.col.aliases': { en: 'Aliases', tr: 'Alias’lar' },
  'cli.reference.col.flags': { en: 'Flags', tr: 'Bayraklar' },
  'cli.reference.col.argument': { en: 'Argument', tr: 'Argüman' },
  'cli.reference.col.required': { en: 'Required', tr: 'Zorunlu' },
  'cli.reference.col.variadic': { en: 'Variadic', tr: 'Variadic' },
  'cli.reference.effect.group': { en: 'Command group (help only)', tr: 'Komut grubu (yalnız help)' },
  'cli.reference.effect.read': { en: 'Read-only', tr: 'Salt-okunur' },
  'cli.reference.effect.mixed': {
    en: 'Read by default; explicit options may mutate state',
    tr: 'Varsayılan salt-okunur; explicit seçenekler state değiştirebilir',
  },
  'cli.reference.effect.local-write': { en: 'Local write', tr: 'Yerel yazma' },
  'cli.reference.effect.process': { en: 'Process control', tr: 'Process kontrolü' },
  'cli.reference.effect.dangerous': { en: 'Destructive process control', tr: 'Yıkıcı process kontrolü' },
  'cli.reference.effect.autonomous': { en: 'Autonomous loop control', tr: 'Autonomous loop kontrolü' },
  'cli.reference.execution.read': { en: 'Read', tr: 'Oku' },
  'cli.reference.execution.dry-run': { en: 'Preview; explicit apply required', tr: 'Önizleme; explicit apply gerekir' },
  'cli.reference.execution.apply': { en: 'Apply', tr: 'Uygula' },
  'cli.reference.authority.open': { en: 'Open', tr: 'Açık' },
  'cli.reference.authority.operator': { en: 'Operator', tr: 'Operator' },
  'cli.reference.authority.owner': { en: 'Owner', tr: 'Owner' },
  'cli.reference.output.text': { en: 'Text', tr: 'Metin' },
  'cli.reference.output.json': { en: 'JSON', tr: 'JSON' },
  'cli.reference.output.text-and-json': { en: 'Text and JSON', tr: 'Metin ve JSON' },
  'cli.reference.output.stream': { en: 'Stream', tr: 'Stream' },
});
