import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { cliContracts } from '../../src/core/cli-command-contract.js';
import {
  CLI_COMMANDS,
  buildCliCommandRows,
  collectCliDocGenerations,
  generateCliDocs,
} from '../../scripts/generate-cli-docs.js';

const ROOT = process.cwd();
const EN_PATH = join(ROOT, 'docs/generated/en/reference/cli.md');
const TR_PATH = join(ROOT, 'docs/generated/tr/reference/cli.md');
const MANIFEST_PATH = join(ROOT, 'docs/generated/cli-manifest.json');

describe('generated CLI reference', () => {
  it('is present in both languages and is generated by one canonical producer', () => {
    expect(existsSync(EN_PATH)).toBe(true);
    expect(existsSync(TR_PATH)).toBe(true);
    expect(existsSync(MANIFEST_PATH)).toBe(true);
    expect(readFileSync(EN_PATH, 'utf8')).toContain('canonical CLI contract');
    expect(readFileSync(TR_PATH, 'utf8')).toContain('Canonical CLI contract');
  });

  it('documents every public contract path and omits the hidden runtime child', () => {
    const content = readFileSync(EN_PATH, 'utf8');
    const visible = cliContracts().filter((contract) => !contract.hidden);
    for (const contract of visible) {
      expect(content).toContain(`deckent ${contract.path.join(' ')}`);
    }
    expect(content).not.toContain('deckent gateway-runtime');
  });

  it('publishes the hidden path in the internal bilingual manifest', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as {
      schemaVersion: number;
      commands: Array<{
        path: string;
        hidden: boolean;
        description: { en: string; tr: string };
        options: Array<{ flags: string; hidden: boolean }>;
      }>;
    };
    expect(manifest.schemaVersion).toBe(1);
    expect(manifest.commands).toHaveLength(cliContracts().length);
    expect(manifest.commands.find((command) => command.path === 'gateway-runtime')).toMatchObject({ hidden: true });
    expect(manifest.commands.every((command) => command.description.en && command.description.tr)).toBe(true);
    expect(manifest.commands.find((command) => command.path === 'start')?.options)
      .toContainEqual(expect.objectContaining({ flags: '--exact-attempt-id <id>', hidden: true }));
  });

  it('keeps internal options out of both public references', () => {
    for (const content of [readFileSync(EN_PATH, 'utf8'), readFileSync(TR_PATH, 'utf8')]) {
      expect(content).not.toContain('`--exact-attempt-id <id>`');
      expect(content).not.toContain('`--exact-owner-nonce <nonce>`');
      expect(content).not.toContain('`--exact-log-ref <path>`');
      expect(content).not.toContain('`--test-mode`');
      expect(content).not.toContain('`--outcome-file <path>`');
    }
  });

  it('contains option, argument, and execution-contract tables', () => {
    const content = readFileSync(EN_PATH, 'utf8');
    expect(content).toContain('### Options');
    expect(content).toContain('### Arguments');
    expect(content).toContain('### Execution contract');
    expect(content).toContain('`--dry-run`');
    expect(content).toContain('`<goal>`');
    expect(content).toContain('Command group (help only)');
    expect(content).toContain('Read by default; explicit options may mutate state');
  });

  it('contains none of the stale source-parser or known-gap projections', () => {
    for (const path of [EN_PATH, TR_PATH]) {
      const content = readFileSync(path, 'utf8');
      expect(content).not.toContain('0 commands');
      expect(content).not.toContain('Source-parsed');
      expect(content).not.toContain('Kaynaktan ayrıştırılır');
      expect(content).not.toContain('Known CLI truth gaps');
      expect(content).not.toContain('Bilinen CLI truth gap');
    }
  });
});

describe('scripts/generate-cli-docs.ts', () => {
  it('derives CLI_COMMANDS from the complete visible contract', () => {
    expect(CLI_COMMANDS).toHaveLength(cliContracts().filter((contract) => !contract.hidden).length);
    expect(CLI_COMMANDS.length).toBeGreaterThan(100);
  });

  it('builds complete EN/TR rows from the live Commander tree', () => {
    const en = buildCliCommandRows('en');
    const tr = buildCliCommandRows('tr');
    expect(en.map((row) => row.path)).toEqual(tr.map((row) => row.path));
    expect(en.every((row) => row.description.length > 0)).toBe(true);
    expect(tr.every((row) => row.description.length > 0)).toBe(true);
    expect(en.flatMap((row) => row.options).every((option) => option.description.length > 0)).toBe(true);
    expect(tr.flatMap((row) => row.arguments).every((argument) => argument.description.length > 0)).toBe(true);
  });

  it('renders deterministically and rejects an empty command projection', () => {
    expect(generateCliDocs(CLI_COMMANDS, 'en')).toBe(generateCliDocs(CLI_COMMANDS, 'en'));
    expect(() => generateCliDocs([], 'en')).toThrow('E_CLI_DOC_EMPTY_COMMAND_SET');
  });

  it('reports every generated target in sync', () => {
    const generations = collectCliDocGenerations(ROOT);
    expect(generations.map((generation) => generation.target)).toEqual([
      'docs/generated/en/reference/cli.md',
      'docs/generated/tr/reference/cli.md',
      'docs/generated/cli-manifest.json',
    ]);
    expect(generations.filter((generation) => generation.drift)).toEqual([]);
  });
});
