// src/core/adr-seed.ts

/**
 * ADR Seed Data — extracted from .brain/DECISIONS.md (Sprint 143 archive).
 * Used by deckent init to preload Memory V2 DB with project ADRs.
 *
 * These are compact summaries. Full ADR content is archived at:
 * .brain/archive/decisions-root-pre-sprint143/DECISIONS.md
 */

import type { CreateEntryInput } from './memory-types.js';

/** All ADRs from the original DECISIONS.md, ready for DB insert. */
export const ADR_SEED_DATA: CreateEntryInput[] = [
  {
    id: 'adr-001',
    type: 'adr',
    title: 'TypeScript + ESM',
    content: 'Use TypeScript with `"type": "module"` (ESM) as the project foundation.',
    summary: 'Use TypeScript with `"type": "module"` (ESM) as the project foundation.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-002',
    type: 'adr',
    title: 'Node16 Module Resolution',
    content: 'Use `"module": "Node16"` and `"moduleResolution": "Node16"` in tsconfig.',
    summary: 'Use `"module": "Node16"` and `"moduleResolution": "Node16"` in tsconfig.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-003',
    type: 'adr',
    title: 'vitest over Jest',
    content: 'Use vitest for testing.',
    summary: 'Use vitest for testing.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-004',
    type: 'adr',
    title: '3-Layer Config Merge',
    content: 'Config loads in 3 layers: hardcoded defaults → `~/.deckent/config.json` → `.deckent/config.json`.',
    summary: 'Config loads in 3 layers: hardcoded defaults → `~/.deckent/config.json` → `.deckent/config.json`.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-005',
    type: 'adr',
    title: 'Synchronous I/O',
    content: 'Wave 2 modülleri (tmux, auditor, worker) senkron I/O kullanır.',
    summary: 'Wave 2 modülleri (tmux, auditor, worker) senkron I/O kullanır.',
    source: 'import',
    status: 'deprecated',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-006',
    type: 'adr',
    title: 'spawnSync Security Pattern',
    content: 'Tüm shell komutları `spawnSync(binary, [...args])` ile çalıştırılır, shell interpretation yok.',
    summary: 'Tüm shell komutları `spawnSync(binary, [...args])` ile çalıştırılır, shell interpretation yok.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-007',
    type: 'adr',
    title: 'SpawnOptions Interface',
    content: '`SpawnOptions { allowedTools?: string; autoApprove?: boolean }` tmux modülünde tanımlanır.',
    summary: '`SpawnOptions { allowedTools?: string; autoApprove?: boolean }` tmux modülünde tanımlanır.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-008',
    type: 'adr',
    title: 'Brain Merkezi Import — Tek Yönlü Bağımlılık',
    content: 'Brain, projede diğer modülleri (tmux, auditor, worker) import eden TEK modüldür. Diğer modüller brain\'i import etmez.',
    summary: 'Brain, projede diğer modülleri (tmux, auditor, worker) import eden TEK modüldür. Diğer modüller brain\'i import etmez.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-009',
    type: 'adr',
    title: 'DEBT.md Markdown Tablo Formatı',
    content: 'AMENDED (Task #4, saf DB-first): Tech debt artık Memory V2 SQLite DB\'sinde (`memory.db`, `type=debt` kayıtları) tutulur — kök `.brain/DEBT.md` dosyası kaldırıldı. İnsan-okur görünüm DB\'den üretilen `.brain/exports/debt.md` (9 kolonlu tablo). ORİJİNAL: DEBT.md 9 kolonlu markdown tablo, `parseDebtTable`/`generateDebtTable` ile okunur/yazılırdı.',
    summary: 'Tech debt Memory V2 DB\'sine taşındı (memory.db, type=debt); .brain/exports/debt.md üretilen görünüm. Kök DEBT.md kaldırıldı (Task #4).',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-010',
    type: 'adr',
    title: 'Minimal Runtime Dependencies (Amended Sprint 143)',
    content: 'Projenin runtime bağımlılıkları minimal tutulur. İzin verilen 4 bağımlılık ve gerekçeleri:\n\n1. **commander** (`^13.0.0`) — CLI framework, 40+ komut yönetimi. Node built-in readline yetersiz.\n2. **better-sqlite3** — Memory V2 DB-first architecture (ADR sprint-131). FTS5 full-text search, field-level history. Pure JS alternatifi yok.\n3. **@modelcontextprotocol/sdk** — MCP server standardı (22 tool, 8 resource). Protokol uyumluluğu için zorunlu.\n4. **zod** — Runtime schema validation (task JSON, config merge, API input). TypeScript compile-time güvencesi runtime\'da yetersiz.\n\nEklenmeyecekler: chalk, inquirer, picocolors, express, fastify, lodash ve benzeri. Yeni bağımlılık eklenmeden önce ADR amendment gerekir. Layer 4 runtime enforcement (T-143-014) bu kuralı otomatik denetler.',
    summary: 'Runtime bağımlılıkları minimal tutulur: commander, better-sqlite3, @modelcontextprotocol/sdk, zod. Yeni bağımlılık için ADR amendment gerekir.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr', 'dependencies'],
  },
  {
    id: 'adr-011',
    type: 'adr',
    title: 'node:readline/promises — Built-in Prompt',
    content: 'İnteraktif prompt\'lar (text, select, confirm) için `node:readline/promises` modülü kullanılır.',
    summary: 'İnteraktif prompt\'lar (text, select, confirm) için `node:readline/promises` modülü kullanılır.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-012',
    type: 'adr',
    title: 'register\\<Name\\>(program) Pattern',
    content: 'Her CLI komutu kendi dosyasında tanımlanır ve `register<Name>(program: Command): void` fonksiyonu export eder.',
    summary: 'Her CLI komutu kendi dosyasında tanımlanır ve `register<Name>(program: Command): void` fonksiyonu export eder.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-013',
    type: 'adr',
    title: 'DECKENT.md Adapter Pattern (Sprint 15)',
    content: 'DECKENT.md = tek gerçek kaynak. CLAUDE.md ve AGENTS.md adaptör dosyalar — sadece `@DECKENT.md` referansı enjekte edilir (ensureDeckentImport). Asla üzerine yazılmaz.',
    summary: 'DECKENT.md = tek gerçek kaynak. CLAUDE.md ve AGENTS.md adaptör dosyalar — sadece `@DECKENT.md` referansı enjekte edilir (ensureDeckentImport). Asla üzerine yazılmaz.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-014',
    type: 'adr',
    title: '.deck Secret File System (Sprint 044)',
    content: 'Ayrı `.deck` dosyası oluşturuldu. DECKENT_ prefix\'li key\'ler bu dosyada tutulur. Init sırasında `.deck` otomatik olarak `.gitignore`\'a eklenir.',
    summary: 'Ayrı `.deck` dosyası oluşturuldu. DECKENT_ prefix\'li key\'ler bu dosyada tutulur. Init sırasında `.deck` otomatik olarak `.gitignore`\'a eklenir.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-015',
    type: 'adr',
    title: 'TaskRouter Module — 6-level routing (Sprint 044)',
    content: 'Ayrı `TaskRouter` modülü oluşturuldu. 6 seviyeli öncelik sırası: config → force → agent → skill → worker → fallback.',
    summary: 'Ayrı `TaskRouter` modülü oluşturuldu. 6 seviyeli öncelik sırası: config → force → agent → skill → worker → fallback.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-016',
    type: 'adr',
    title: 'Connector Module — provider lifecycle (Sprint 044)',
    content: '`Connector` class ile runtime health check, lazy init ve auditor entegrasyonu sağlandı. Her provider bağlantısı Connector üzerinden yönetilir.',
    summary: '`Connector` class ile runtime health check, lazy init ve auditor entegrasyonu sağlandı. Her provider bağlantısı Connector üzerinden yönetilir.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-017',
    type: 'adr',
    title: 'MCP-Native Provider Adapters (Sprint 045)',
    content: 'Gerçek CLI komutlarına geçiş: `codex exec --full-auto` ve `gemini -p --output-format json`. Adapter\'lar gerçek binary\'leri wrap eder.',
    summary: 'Gerçek CLI komutlarına geçiş: `codex exec --full-auto` ve `gemini -p --output-format json`. Adapter\'lar gerçek binary\'leri wrap eder.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-018',
    type: 'adr',
    title: 'Multi-Environment Config Generation (Sprint 046)',
    content: 'Ortam başına config generator: Codex → `config.toml`, Gemini → `settings.json`, Cursor → `mcp.json`. `deckent init --all-envs` tüm ortamları tek seferde hazırlar.',
    summary: 'Ortam başına config generator: Codex → `config.toml`, Gemini → `settings.json`, Cursor → `mcp.json`. `deckent init --all-envs` tüm ortamları tek seferde hazırlar.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-019',
    type: 'adr',
    title: 'Language-Agnostic Worker Verify (Sprint 046)',
    content: '`STACK_COMMANDS` ile dil bazlı build/test komutu belirlendi: Python → `pytest`, Go → `go test ./...`, Rust → `cargo test`. `.deckent/project-stack.json` dosyasından stack okunur.',
    summary: '`STACK_COMMANDS` ile dil bazlı build/test komutu belirlendi: Python → `pytest`, Go → `go test ./...`, Rust → `cargo test`. `.deckent/project-stack.json` dosyasından stack okunur.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-020',
    type: 'adr',
    title: 'Rich Sprint Output — 7-section summary (Sprint 044)',
    content: '7 bölümlü rich output: Header, Results, Changes, Tests, Agents, Learnings, Next Steps. ANSI renk desteği ve `NO_COLOR` env var desteği eklendi.',
    summary: '7 bölümlü rich output: Header, Results, Changes, Tests, Agents, Learnings, Next Steps. ANSI renk desteği ve `NO_COLOR` env var desteği eklendi.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-021',
    type: 'adr',
    title: 'Kraken ASCII Brand Identity (Sprint 044)',
    content: 'Kraken ASCII mascot: teal gövde (#4db8a4), gold DECKENT yazısı (#c4a855), dim tagline. `deckent --version` ve `deckent init` komutlarında splash gösterilir.',
    summary: 'Kraken ASCII mascot: teal gövde (#4db8a4), gold DECKENT yazısı (#c4a855), dim tagline. `deckent --version` ve `deckent init` komutlarında splash gösterilir.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-022',
    type: 'adr',
    title: 'CLI/MCP Feature Parity — Tek Yapı, Çoklu Ortam (Sprint 067)',
    content: 'CLI ve MCP tam özellik eşliği (feature parity) sağlanmalı. Her yeni CLI komutu aynı zamanda MCP tool olarak da kaydedilmeli. Ortak iş mantığı `src/core/` veya `src/orchestra/` altında paylaşılan fonksiyonlarda olmalı — CLI ve MCP sadece thin wrapper (giriş/çıkış adaptörü). Yeni özellik eklerken:',
    summary: 'CLI ve MCP tam özellik eşliği (feature parity) sağlanmalı. Her yeni CLI komutu aynı zamanda MCP tool olarak da kaydedilmeli. Ortak iş mantığı `src/core/` veya `src/orchestra/` altında paylaşılan fonksiyonlarda olmalı — CLI ve MCP sadece thin wrapper (giriş/çıkış adaptörü). Yeni özellik eklerken:',
    source: 'import',
    status: 'superseded',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-023',
    type: 'adr',
    title: 'Plan Tier Generalizasyonu — Provider-Agnostic Tier İsimleri (Sprint 072)',
    content: 'Tier isimleri genelleştirildi:',
    summary: 'Tier isimleri genelleştirildi:',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-024',
    type: 'adr',
    title: 'sprint-controller.ts God Object Split — sprint-phases.ts Extract (Sprint 072)',
    content: 'Sprint fazları `sprint-phases.ts` adlı yeni dosyaya çıkarıldı. `runSprint()` içindeki 7 faz fonksiyonu extract edildi:',
    summary: 'Sprint fazları `sprint-phases.ts` adlı yeni dosyaya çıkarıldı. `runSprint()` içindeki 7 faz fonksiyonu extract edildi:',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-025',
    type: 'adr',
    title: 'Graceful Shutdown Stratejisi — SIGINT → interruptActiveSprint (Sprint 076)',
    content: '`entry.ts` içindeki SIGINT handler genişletildi:',
    summary: '`entry.ts` içindeki SIGINT handler genişletildi:',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-026',
    type: 'adr',
    title: 'God Object Split Stratejisi — Faz 1-3 Tamamlandı (Sprint 076)',
    content: '3 fazlı kademeli split stratejisi:',
    summary: '3 fazlı kademeli split stratejisi:',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-022-v2',
    type: 'adr',
    title: 'CLI/MCP Feature Parity — Parametre Eşitleme + Eksik Komutlar (Updated Sprint 085)',
    content: 'CLI-only komutlar altyapı/terminal işlemleridir ve MCP\'de yer almaz:',
    summary: 'CLI-only komutlar altyapı/terminal işlemleridir ve MCP\'de yer almaz:',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-027',
    type: 'adr',
    title: 'Hybrid Spawn Backend (Sprint 123, Revisited Sprint 139)',
    content: 'Hibrit backend desteği **kalıcı olarak reddedildi** (Option B: reject). Mevcut tek-backend modeli yeterli ve Sprint 139 backend parity çalışması bu kararı güçlendirdi. `SpawnBackendFactory` docker → tmux → subprocess fallback zinciriyle TEK bir backend seçer; hibrit mod (worker Docker\'da, auditor subprocess olarak) implementasyona alınmayacak.',
    summary: 'Hibrit backend desteği **kalıcı olarak reddedildi** (Option B: reject). Mevcut tek-backend modeli yeterli ve Sprint 139 backend parity çalışması bu kararı güçlendirdi. `SpawnBackendFactory` docker → tmux → subprocess fallback zinciriyle TEK bir backend seçer; hibrit mod (worker Docker\'da, auditor subprocess olarak) implementasyona alınmayacak.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-028',
    type: 'adr',
    title: 'Decision-Engine V1 → V2 Routing Migration',
    content: 'V1 kod silinmeyecek — referans implementasyonu olarak korunacak. @deprecated ile işaretlendi.',
    summary: 'V1 kod silinmeyecek — referans implementasyonu olarak korunacak. @deprecated ile işaretlendi.',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-029',
    type: 'adr',
    title: 'Managed-Docs Universalization — Sprint Lifecycle Template-Based Document Generation',
    content: 'Managed-Docs Universalization — Sprint Lifecycle Template-Based Document Generation',
    summary: 'Managed-Docs Universalization — Sprint Lifecycle Template-Based Document Generation',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-030',
    type: 'adr',
    title: 'Template Engine + Plugin Loader — Managed-Docs Render Pipeline',
    content: 'Template Engine + Plugin Loader — Managed-Docs Render Pipeline',
    summary: 'Template Engine + Plugin Loader — Managed-Docs Render Pipeline',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-031',
    type: 'adr',
    title: 'Content Hash Cache — Sprint Dokümanları Hash-Based Invalidation',
    content: 'Content Hash Cache — Sprint Dokümanları Hash-Based Invalidation',
    summary: 'Content Hash Cache — Sprint Dokümanları Hash-Based Invalidation',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-032',
    type: 'adr',
    title: 'i18n Pattern System — TR/EN İçerik Çeşitliliği Desteği',
    content: 'i18n Pattern System — TR/EN İçerik Çeşitliliği Desteği',
    summary: 'i18n Pattern System — TR/EN İçerik Çeşitliliği Desteği',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-033',
    type: 'adr',
    title: 'Product Vision — Product Not Service',
    content: 'Product Vision — Product Not Service',
    summary: 'Product Vision — Product Not Service',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-034',
    type: 'adr',
    title: 'Multi-Project Isolation — Per-Project Security Boundaries',
    content: 'Multi-Project Isolation — Per-Project Security Boundaries',
    summary: 'Multi-Project Isolation — Per-Project Security Boundaries',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-035',
    type: 'adr',
    title: 'Brain ↔ Worker ↔ Auditor Verification Protocol Standard (Sprint 138)',
    content: 'Brain ↔ Worker ↔ Auditor Verification Protocol Standard (Sprint 138)',
    summary: 'Brain ↔ Worker ↔ Auditor Verification Protocol Standard (Sprint 138)',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-036',
    type: 'adr',
    title: 'ADR Governance Integration — Mandatory Architecture Decision Enforcement',
    content: 'ADR Governance Integration — Mandatory Architecture Decision Enforcement',
    summary: 'ADR Governance Integration — Mandatory Architecture Decision Enforcement',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-037',
    type: 'adr',
    title: 'Brain-Auditor-Worker Authority Matrix — RBAC Protocol V1.0',
    content: 'Brain-Auditor-Worker Authority Matrix — RBAC Protocol V1.0',
    summary: 'Brain-Auditor-Worker Authority Matrix — RBAC Protocol V1.0',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-038',
    type: 'adr',
    title: 'Dead Code Disposition — Sprint 139 Audit Results',
    content: 'Dead Code Disposition — Sprint 139 Audit Results',
    summary: 'Dead Code Disposition — Sprint 139 Audit Results',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
  {
    id: 'adr-039',
    type: 'adr',
    title: 'Self-Modifying Task Detection — Deckent Dogfood vs User Project Discrimination',
    content: 'Self-Modifying Task Detection — Deckent Dogfood vs User Project Discrimination',
    summary: 'Self-Modifying Task Detection — Deckent Dogfood vs User Project Discrimination',
    source: 'import',
    status: 'accepted',
    decay_exempt: true,
    tags: ['architecture', 'adr'],
  },
];

/** Identity entry seed for new project init. */
export function createIdentitySeed(projectName: string): CreateEntryInput {
  return {
    id: 'identity-project',
    type: 'identity',
    title: `Project Identity: ${projectName}`,
    content: `Project ${projectName} initialized with Deckent.`,
    source: 'system',
    status: 'active',
    decay_exempt: true,
    tags: ['identity', 'project'],
  };
}
