// ─── `deckent plan-nl` — Free-form goal → DIRECTIVES.md scaffold (DIR-1-CMD,
// Sprint 354 Task 354-008) ──────────────────────────────────────────────
//
// Wraps the pure directives-builder core (buildDirectives, Sprint 354 Task
// 354-007/DIR-1) into a real CLI command. `buildPlanNlIntent` is the ONLY
// "structured intent" this task produces — a single-task template mapped
// directly from the goal text, with Files/Scope/goCriteria/nogo left as
// explicit TODO placeholders. Turning the goal into a real multi-task plan
// (NL understanding, file/scope inference) is an explicit follow-up (the
// "LLM layer") — this command deliberately stops at deterministic templating,
// same boundary directives-builder.ts itself draws for markdown generation.
//
// Default behavior is a dry-run preview to stdout; DIRECTIVES.md is only
// touched with `--write`, and only ever after backing up any existing file
// (timestamped `.bak.<iso>`, mirroring the pattern in
// core/config-migration.ts — reimplemented inline here since that module is
// outside this task's scope and the logic is a few lines).
//
// TERM-FLOW-UNIFY Sprint-6 (428-007, docs/analysis/term-flow-unify-design-
// 2026-07-11.md "Ölecek / compatibility-only parçalar"): buildPlanNlIntent
// dies as the RUNTIME-CANONICAL preview source once `terminal.run_flow_v2`
// is on — the preview command becomes a compatibility-preview-adapter that
// delegates to the shared plan-preview-service (the same real Brain-planner
// path CLI `plan --dry-run` / MCP `deckent_plan` already use), forcing
// `structured` mode so the command stays the deterministic, LLM-free
// scaffold it has always been. The scaffold markdown is fed to the real
// planner in-memory only (DIRECTIVES.md on disk is never touched by the
// preview path); the printed preview shape is unchanged, with one added
// compatibility line surfacing the real plan digest. Flag-off (default) and
// `--write` are entirely unaffected — see registerPlanNl's action handler.

import { existsSync, copyFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Command } from 'commander';
import { DIRECTIVES_FILE } from '../../core/constants.js';
import { buildDirectives, type DirectiveBuildIntent } from '../../orchestra/directives-builder.js';
import { readContext } from '../../orchestra/brain.js';
import { generatePlanPreview, type PlanPreviewResult } from '../../orchestra/plan-preview-service.js';
import { loadConfig } from '../../core/config.js';
import type { ResolvedConfig, SprintSizeRecommendation } from '../../core/types.js';
import { resolveProjectRoot } from '../helpers/process.js';
import { getLangFromConfig } from '../helpers/config-reader.js';
import { getMessage } from '../helpers/messages.js';
import { print, printError } from '../helpers/output.js';

export interface PlanNlCommandOptions {
  write?: boolean;
}

/**
 * Map a free-form NL goal to a single-task {@link DirectiveBuildIntent}
 * scaffold. Files/Scope/goCriteria/nogo are explicit TODO placeholders — see
 * module doc comment for why this stops short of real decomposition.
 */
export function buildPlanNlIntent(goal: string): DirectiveBuildIntent {
  const trimmedGoal = goal.trim();
  return {
    title: 'plan-nl scaffold',
    goal: trimmedGoal,
    tasks: [
      {
        title: trimmedGoal,
        desc:
          `${trimmedGoal}\n\n` +
          'Auto-generated by `deckent plan-nl` from the goal above — this is a single-task ' +
          'SCAFFOLD, not a ready-to-run plan. NL to multi-task decomposition is a follow-up ' +
          '(LLM layer); fill in the TODO placeholders below to match the real work before ' +
          'running `deckent plan` / `deckent start` on it.',
        files: ['TODO-fill-in-target-files'],
        scope: ['TODO-fill-in-scope/'],
        deps: [],
        goCriteria: [`TODO: define verifiable done-criteria for "${trimmedGoal}"`],
        nogo: ['TODO: define what must NOT happen'],
      },
    ],
  };
}

/** Wraps the generated DIRECTIVES.md text with an explicit dry-run banner. */
export function formatPlanNlPreview(directivesText: string): string {
  return [
    'Deckent Plan (NL) — preview only, DIRECTIVES.md was NOT modified. Re-run with --write to save.',
    '',
    directivesText,
  ].join('\n');
}

/**
 * TERM-FLOW-UNIFY Sprint-6 (428-007) compatibility-preview-adapter: renders
 * the plan-nl preview through the shared plan-preview-service instead of
 * treating the buildPlanNlIntent scaffold as the final answer. The scaffold
 * markdown is substituted into the real project's {@link BrainContext}
 * in-memory only (`readContext`'s own `directives` field is overridden) —
 * DIRECTIVES.md on disk is never read from or written to here, preserving
 * plan-preview-service's own READ-ONLY-by-construction guarantee. `structured`
 * mode is forced so this stays a deterministic, LLM-free preview, matching
 * buildPlanNlIntent's existing single-task-scaffold boundary.
 */
export async function buildPlanNlCompatibilityPreview(
  root: string,
  config: ResolvedConfig,
  directivesMarkdown: string,
): Promise<PlanPreviewResult> {
  const context = readContext(root);
  const recommendation: SprintSizeRecommendation = {
    size: 'full',
    maxWorkers: typeof config.activeModeConfig.max_workers === 'number' ? config.activeModeConfig.max_workers : 4,
    modelConstraint: null,
    reason: 'plan-nl compatibility-preview-adapter (TERM-FLOW-UNIFY Sprint-6, 428-007)',
  };
  return generatePlanPreview(root, config, { ...context, directives: directivesMarkdown }, recommendation, {
    mode: 'structured',
  });
}

function backupExistingDirectives(directivesPath: string): string | null {
  if (!existsSync(directivesPath)) return null;
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = `${directivesPath}.bak.${timestamp}`;
  copyFileSync(directivesPath, backupPath);
  return backupPath;
}

export function registerPlanNl(program: Command): void {
  program
    .command('plan-nl')
    .description('Turn a free-form goal into a DIRECTIVES.md scaffold (single-task template; preview by default)')
    .argument('<goal>', 'Free-form description of what the sprint should accomplish')
    .option('--write', 'Write the scaffold to DIRECTIVES.md (any existing file is backed up first)')
    .action(async (goal: string, opts: PlanNlCommandOptions) => {
      const trimmedGoal = goal.trim();
      if (!trimmedGoal) {
        printError('plan-nl: goal must not be empty');
        process.exitCode = 1;
        return;
      }

      let root: string;
      try {
        root = resolveProjectRoot();
      } catch {
        root = process.cwd();
      }
      const lang = getLangFromConfig(root);

      let text: string;
      try {
        text = buildDirectives(buildPlanNlIntent(trimmedGoal));
      } catch (error) {
        printError(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
        return;
      }

      if (!opts.write) {
        const config = await loadConfig(root);
        if (config.terminal?.run_flow_v2 === true) {
          try {
            const preview = await buildPlanNlCompatibilityPreview(root, config, text);
            print(formatPlanNlPreview(text));
            print(
              `[plan-nl] compatibility-preview-adapter (terminal.run_flow_v2): real plan digest ${preview.planDigest}.`,
            );
          } catch (error) {
            printError(error instanceof Error ? error.message : String(error));
            process.exitCode = 1;
          }
          return;
        }
        print(formatPlanNlPreview(text));
        return;
      }

      const directivesPath = join(root, DIRECTIVES_FILE);
      const backupPath = backupExistingDirectives(directivesPath);
      writeFileSync(directivesPath, text, 'utf-8');

      if (backupPath) {
        print(`Backed up existing DIRECTIVES.md → ${backupPath}`);
      }
      print(getMessage('set_directives.updated', lang, { count: '1' }));
    });
}
