// ─── `deckent plan-nl` — Free-form goal → DIRECTIVES.md scaffold (DIR-1-CMD,
// Sprint 354 Task 354-008) ──────────────────────────────────────────────
//
// Wraps the pure directives-builder core (buildDirectives, Sprint 354 Task
// 354-007/DIR-1) into a real CLI command. `buildPlanNlIntent` is the ONLY
// "structured intent" this task produces — a single-task template mapped
// directly from the goal text, with Files/Scope/goCriteria/nogo left as
// explicit TODO placeholders. Turning the goal into a real multi-task plan
// (NL understanding, file/scope inference) is an explicit follow-up (the
// "LLM layer") — this command deliberately stops at deterministic templating,
// same boundary directives-builder.ts itself draws for markdown generation.
//
// Default behavior is a dry-run preview to stdout; DIRECTIVES.md is only
// touched with `--write`, and only ever after backing up any existing file
// (timestamped `.bak.<iso>`, mirroring the pattern in
// core/config-migration.ts — reimplemented inline here since that module is
// outside this task's scope and the logic is a few lines).

import { existsSync, copyFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Command } from 'commander';
import { DIRECTIVES_FILE } from '../../core/constants.js';
import { buildDirectives, type DirectiveBuildIntent } from '../../orchestra/directives-builder.js';
import { resolveProjectRoot } from '../helpers/process.js';
import { getLangFromConfig } from '../helpers/config-reader.js';
import { getMessage } from '../helpers/messages.js';
import { print, printError } from '../helpers/output.js';

export interface PlanNlCommandOptions {
  write?: boolean;
}

/**
 * Map a free-form NL goal to a single-task {@link DirectiveBuildIntent}
 * scaffold. Files/Scope/goCriteria/nogo are explicit TODO placeholders — see
 * module doc comment for why this stops short of real decomposition.
 */
export function buildPlanNlIntent(goal: string): DirectiveBuildIntent {
  const trimmedGoal = goal.trim();
  return {
    title: 'plan-nl scaffold',
    goal: trimmedGoal,
    tasks: [
      {
        title: trimmedGoal,
        desc:
          `${trimmedGoal}\n\n` +
          'Auto-generated by `deckent plan-nl` from the goal above — this is a single-task ' +
          'SCAFFOLD, not a ready-to-run plan. NL to multi-task decomposition is a follow-up ' +
          '(LLM layer); fill in the TODO placeholders below to match the real work before ' +
          'running `deckent plan` / `deckent start` on it.',
        files: ['TODO-fill-in-target-files'],
        scope: ['TODO-fill-in-scope/'],
        deps: [],
        goCriteria: [`TODO: define verifiable done-criteria for "${trimmedGoal}"`],
        nogo: ['TODO: define what must NOT happen'],
      },
    ],
  };
}

/** Wraps the generated DIRECTIVES.md text with an explicit dry-run banner. */
export function formatPlanNlPreview(directivesText: string): string {
  return [
    'Deckent Plan (NL) — preview only, DIRECTIVES.md was NOT modified. Re-run with --write to save.',
    '',
    directivesText,
  ].join('\n');
}

function backupExistingDirectives(directivesPath: string): string | null {
  if (!existsSync(directivesPath)) return null;
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = `${directivesPath}.bak.${timestamp}`;
  copyFileSync(directivesPath, backupPath);
  return backupPath;
}

export function registerPlanNl(program: Command): void {
  program
    .command('plan-nl')
    .description('Turn a free-form goal into a DIRECTIVES.md scaffold (single-task template; preview by default)')
    .argument('<goal>', 'Free-form description of what the sprint should accomplish')
    .option('--write', 'Write the scaffold to DIRECTIVES.md (any existing file is backed up first)')
    .action(async (goal: string, opts: PlanNlCommandOptions) => {
      const trimmedGoal = goal.trim();
      if (!trimmedGoal) {
        printError('plan-nl: goal must not be empty');
        process.exitCode = 1;
        return;
      }

      let root: string;
      try {
        root = resolveProjectRoot();
      } catch {
        root = process.cwd();
      }
      const lang = getLangFromConfig(root);

      let text: string;
      try {
        text = buildDirectives(buildPlanNlIntent(trimmedGoal));
      } catch (error) {
        printError(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
        return;
      }

      if (!opts.write) {
        print(formatPlanNlPreview(text));
        return;
      }

      const directivesPath = join(root, DIRECTIVES_FILE);
      const backupPath = backupExistingDirectives(directivesPath);
      writeFileSync(directivesPath, text, 'utf-8');

      if (backupPath) {
        print(`Backed up existing DIRECTIVES.md → ${backupPath}`);
      }
      print(getMessage('set_directives.updated', lang, { count: '1' }));
    });
}
